PRODUCTO_ID = 0
TITULO = 1
AUTOR = 2
EDITORIAL = 3
GENERO = 4
PRECIO = 5
EXISTENCIA = 6
FECHA_RESURTIDO = 7

COLUMNAS = ["PRODUCTO_ID", "TITULO", "AUTOR", "EDITORIAL", "GENERO","PRECIO", "EXISTENCIA", "FECHA_RESURTIDO"]
